apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: template
    context: ./src/Zip.Api.CustomerSummary.Api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./src/charts/api-customer-summary/manifests/api-customer-summary/templates/*.yaml