apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: template
    context: .
    docker:
      buildArgs: 
        ARTIFACTORY_USER: "{{ .ARTIFACTORY_USER }}"
        ARTIFACTORY_PASS: "{{ .ARTIFACTORY_PASS }}"
      dockerfile: Dockerfile_dev
    sync:
      manual:
        - src: '**/*.cs'
          dest: /app/

deploy:
  kubectl:
    manifests:
    - ./charts/zip-api-customerprofile/manifests/zip-api-customerprofile/templates/*.yaml