version: '3.7'

services:
  taurus:
    image: blazemeter/taurus
    network_mode: host
    ulimits:
      nproc: 65535
      nofile:
        soft: 90000
        hard: 90000
    volumes:
      - .:/bzt-configs