apiVersion: v1
kind: Service
metadata:
  name: {{ include "zip-api-customerprofile.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.container.port }}"
  labels:
{{ include "zip-api-customerprofile.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "zip-api-customerprofile.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  