import randStr from '../../utils/api-helper'


export const requests = {
    validBody: {
    "name": `${randStr.getRandomString(5)}`,
        "abn": "35135776383",
        "address": "Sydney",
        "websiteUrl": "http://www.google.com",
        "directorEmail": `${randStr.getRandomString(5)}@zipteam222898.testinator.com`,
        "adminEmail": `${randStr.getRandomString(5)}@zipteam222898.testinator.com`,
        "directorName": "DirectorName",
        "directorPhone": "0400000000",
        "adminFirstName": "fn-test2021032902",
        "adminLastName": "ln-test2021032902",
        "adminPhone": "0400000000",
        "intendedUse": 1,
        "category": "Cosmetic & Beauty Retailers",
        "subCategory": "Other",
        "bankAccountNumber": "12345678",
        "bsbNumber": "123456",
        "bankAccountName": "test2021032902",
        "websitePlatform": "test website",
        "settlementEmail": "7520e85e37a718f417f9@mailinator.com",
        "v3ApiKey": "ywlpw0RSoxhYT/R39eJR0469kyj6StZABZMhQc/2SYo="
    },
    duplicateEmail: {
        "countryCode": "AU",
        "name": "test2021042901",
        "abn": "11223491505",
        "address": "Sydney",
        "websiteUrl": "http://www.google.com",
        "directorName": "11223491505",
        "directorEmail": `basduplicateemail@mailinator.com`,
        "directorPhone": "0400000000",
        "intendedUse": 1,
        "category": "Cosmetic & Beauty Retailers",
        "subCategory": "Other",
        "bankAccountName": "test-new",
        "bankAccountNumber": "222222",
        "bsbNumber": "999999",
        "websitePlatform": "Shopify2",
        "settlementEmail": "adyen-settle-test@gmail.com"
    },
    missingEmail: {
        "countryCode": "AU",
        "name": "test2021042901",
        "abn": "11223491505",
        "address": "Sydney",
        "websiteUrl": "http://www.google.com",
        "directorName": "11223491505",
        "directorEmail": "",
        "directorPhone": "0400000000",
        "intendedUse": 1,
        "category": "Cosmetic & Beauty Retailers",
        "subCategory": "Other",
        "bankAccountName": "test-new",
        "bankAccountNumber": "222222",
        "bsbNumber": "999999",
        "websitePlatform": "Shopify2",
        "settlementEmail": "bas-testing2@mailinator.com"
    },
    invalidEmail: {
        "countryCode": "AU",
        "name": "test2021042901",
        "abn": "11223491505",
        "address": "Sydney",
        "websiteUrl": "http://www.google.com",
        "directorName": "11223491505",
        "directorEmail": "meow",
        "directorPhone": "0400000000",
        "intendedUse": 1,
        "category": "Cosmetic & Beauty Retailers",
        "subCategory": "Other",
        "bankAccountName": "test-new",
        "bankAccountNumber": "222222",
        "bsbNumber": "999999",
        "websitePlatform": "Shopify2",
        "settlementEmail": "bas-testing2@mailinator.com"
    },
    invalidAbn: {
        "countryCode": "AU",
        "name": "test2021042901",
        "abn": "meow",
        "address": "Sydney",
        "websiteUrl": "http://www.google.com",
        "directorName": "11223491505",
        "directorEmail": `${randStr.getRandomString(5)}@zipteam222898.testinator.com`,
        "directorPhone": "0400000000",
        "intendedUse": 1,
        "category": "Cosmetic & Beauty Retailers",
        "subCategory": "Other",
        "bankAccountName": "test-new",
        "bankAccountNumber": "222222",
        "bsbNumber": "999999",
        "websitePlatform": "Shopify2",
        "settlementEmail": "bas-testing2@mailinator.com"
    },
    invalidIntendedUse: {
        "countryCode": "AU",
        "name": "test2021042901",
        "abn": "11223491505",
        "address": "Sydney",
        "websiteUrl": "http://www.google.com",
        "directorName": "11223491505",
        "directorEmail": `${randStr.getRandomString(5)}@zipteam222898.testinator.com`,
        "directorPhone": "0400000000",
        "intendedUse": "money laundering",
        "category": "Cosmetic & Beauty Retailers",
        "subCategory": "Other",
        "bankAccountName": "test-new",
        "bankAccountNumber": "222222",
        "bsbNumber": "999999",
        "websitePlatform": "Shopify2",
        "settlementEmail": "bas-testing2@mailinator.com"
    },
}
export const responses = {
        emptyBody: {
            "errors":[
                "ABN must be 11 digits",
                "ABN must be valid",
                "'Name' should not be empty.",
                "'Trading Name' should not be empty.",
                "'Display Name' should not be empty.",
                "'Website Url' should not be empty.",
                "'Address' should not be empty.",
                "'Admin First Name' should not be empty.",
                "'Admin Last Name' should not be empty.",
                "'Director Name' should not be empty.",
                "'Admin Email' should not be empty.",
                "'Director Email' should not be empty.",
                "'Admin Phone' should not be empty.",
                "'Director Phone' should not be empty."
            ],
            "existingMerchantDetails":null,
            "inStoreApiKey":null,
            "merchantId":null,
            "message":"Request payload is not valid",
            "onlineApiKey":null,
            "status":null,
            "success":false,
            "v3ApiKey":null
        },
        missingEmail: {
            "errors": ["'Admin First Name' should not be empty.", "'Admin Last Name' should not be empty.", "'Admin Email' should not be empty.", "DirectorEmail must be not empty and max 100 letters", "'Admin Phone' should not be empty."],
            "inStoreApiKey": null,
            "merchantId": null,
            "message": "Request payload is not valid",
            "onlineApiKey": null,
            "status": null,
            "success": false,
            "v3ApiKey":null
        },
        emptyEmail: {
            "errors":[
                "'Admin First Name' should not be empty.",
                "'Admin Last Name' should not be empty.",
                "'Admin Email' should not be empty.",
                "'Director Email' should not be empty.",
                "'Director Email' must be between 1 and 100 characters. You entered 0 characters.",
                "DirectorEmail must be not empty and max 100 letters",
                "'Admin Phone' should not be empty."
            ],
            "existingMerchantDetails":null,
            "inStoreApiKey":null,
            "merchantId":null,
            "message":"Request payload is not valid",
            "onlineApiKey":null,
            "status":null,
            "success":false,
            "v3ApiKey":null
        },
        invalidEmail: {
            "errors":[
                "'Admin First Name' should not be empty.",
                "'Admin Last Name' should not be empty.",
                "'Admin Email' should not be empty.",
                "DirectorEmail must be not empty and max 100 letters",
                "'Admin Phone' should not be empty."
            ],
            "existingMerchantDetails":null,
            "inStoreApiKey":null,
            "merchantId":null,
            "message":"Request payload is not valid",
            "onlineApiKey":null,
            "status":null,
            "success":false,
            "v3ApiKey":null
        },
        duplicateEmail: {
            "errors":[
                "'Admin First Name' should not be empty.",
                "'Admin Last Name' should not be empty.",
                "'Admin Email' should not be empty.",
                "'Admin Phone' should not be empty."
            ],
            "existingMerchantDetails":null,
            "inStoreApiKey":null,
            "merchantId":null,
            "message":"Request payload is not valid",
            "onlineApiKey":null,
            "status":null,
            "success":false,
            "v3ApiKey":null
        },
        invalidAbn: {
            "errors":[
                "ABN must be 11 digits",
                "ABN must be valid",
                "'Admin First Name' should not be empty.",
                "'Admin Last Name' should not be empty.",
                "'Admin Email' should not be empty.",
                "'Admin Phone' should not be empty."
            ],
            "existingMerchantDetails":null,
            "inStoreApiKey":null,
            "merchantId":null,
            "message":"Request payload is not valid",
            "onlineApiKey":null,
            "status":null,
            "success":false,
            "v3ApiKey":null
        },
}