# Default values for zip-api-customerprofile.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
probes:
  enabled: true

vaultAccess:
  enabled: false
  url: "https://vault.internal.mgmt.au.edge.zip.co"
  vaultSecretPath: "dev-apse2-main/customer-acquisition/rds/zip-services-customerprofile-dev"
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 300m
      memory: 64Mi

podAnnotations:
  iam.amazonaws.com/role: eks-customer-acquisition-zip_processor_customerprofile_role

image:
  repository: template
  tag: latest
  pullPolicy: IfNotPresent

dbMigration:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 256Mi

imagePullSecrets:
  - name: artifactory-sec
nameOverride: ""
fullnameOverride: ""

container:
  port: 5000

securityContext:
  readOnlyRootFilesystem: false
  runAsUser: 0

service:
  type: ClusterIP
  port: 5001
  
ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: localy.local
      paths:
        - /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

newRelic:
  enabled: false

autoscaling:
  enabled: false

customerProfileDatabase:
  useInMemoryDatabase: false
  host: release-name-postgresql
  database: localDb
  username: postgres

