stages:
  - sandbox_ui_tests

sandbox_ui_tests:
  stage: sandbox_ui_tests
  image: zipau-docker.jfrog.io/playwright:latest
  script:
    - npm ci
    - npm run test:ci
  tags: [ apps-apse2 ]
  artifacts:
    when: on_failure
    paths:
      - output/**